import AppKit
import UniformTypeIdentifiers

/// Единая точка разбора NSPasteboard: используется и монитором буфера обмена,
/// и приёмниками drag & drop (иконка в меню-баре, окно полки).
enum ClipReader {

    /// Типы, которые помечают содержимое как приватное/временное — их не сохраняем.
    private static let ignoredTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
        .init("com.agilebits.onepassword"),
        .init("com.typeit4me.clipping"),
        .init("Pasteboard generator type"),
        .init("de.petermaurer.TransientPasteboardType")
    ]

    static func shouldIgnore(_ pb: NSPasteboard) -> Bool {
        let types = Set(pb.types ?? [])
        return ignoredTypes.contains { types.contains($0) }
    }

    /// Разбирает содержимое доски в один элемент. Возвращает nil, если ничего полезного нет.
    static func read(_ pb: NSPasteboard, isShelf: Bool) -> ClipItem? {
        guard !shouldIgnore(pb) else { return nil }

        if let item = readFiles(pb, isShelf: isShelf) { return item }
        if let item = readImage(pb, isShelf: isShelf) { return item }
        if let item = readRichText(pb, isShelf: isShelf) { return item }
        if let item = readText(pb, isShelf: isShelf) { return item }
        return nil
    }

    // MARK: - Разборщики

    private static func readFiles(_ pb: NSPasteboard, isShelf: Bool) -> ClipItem? {
        let options: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        guard let urls = pb.readObjects(forClasses: [NSURL.self], options: options) as? [URL],
              !urls.isEmpty else { return nil }
        return filesItem(urls: urls, isShelf: isShelf)
    }

    /// Собирает элемент-«файлы» из готового списка путей.
    static func filesItem(urls: [URL], isShelf: Bool) -> ClipItem? {
        guard !urls.isEmpty else { return nil }
        let paths = urls.map(\.path)
        var totalSize = 0
        for url in urls {
            let values = try? url.resourceValues(forKeys: [.totalFileAllocatedSizeKey, .fileSizeKey])
            totalSize += values?.totalFileAllocatedSize ?? values?.fileSize ?? 0
        }

        var item = ClipItem(kind: .files, isShelf: isShelf)
        item.paths = paths
        item.text = paths.joined(separator: "\n")
        item.detail = totalSize > 0 ? Fmt.bytes.string(fromByteCount: Int64(totalSize)) : nil
        item.fingerprint = "files:" + paths.sorted().joined(separator: "|").sha256
        return item
    }

    private static func readImage(_ pb: NSPasteboard, isShelf: Bool) -> ClipItem? {
        let pngType = NSPasteboard.PasteboardType.png
        var data = pb.data(forType: pngType)
        if data == nil, let tiff = pb.data(forType: .tiff) {
            data = NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:])
        }
        guard let png = data, let image = NSImage(data: png) else { return nil }

        guard let name = Blobs.write(png, ext: "png") else { return nil }

        var item = ClipItem(kind: .image, isShelf: isShelf)
        item.blobName = name
        let rep = NSBitmapImageRep(data: png)
        let w = rep?.pixelsWide ?? Int(image.size.width)
        let h = rep?.pixelsHigh ?? Int(image.size.height)
        item.detail = "\(w)×\(h) · " + Fmt.bytes.string(fromByteCount: Int64(png.count))
        item.fingerprint = "image:" + png.sha256
        return item
    }

    private static func readRichText(_ pb: NSPasteboard, isShelf: Bool) -> ClipItem? {
        guard let rtf = pb.data(forType: .rtf),
              let attributed = NSAttributedString(rtf: rtf, documentAttributes: nil),
              !attributed.string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return nil }

        // Простой текст без разметки считаем обычным текстом — так превью честнее.
        let plain = pb.string(forType: .string) ?? attributed.string
        guard let name = Blobs.write(rtf, ext: "rtf") else { return nil }

        var item = ClipItem(kind: .richText, isShelf: isShelf)
        item.text = plain
        item.blobName = name
        item.fingerprint = "rich:" + plain.sha256
        return item
    }

    private static func readText(_ pb: NSPasteboard, isShelf: Bool) -> ClipItem? {
        guard let string = pb.string(forType: .string),
              !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        else { return nil }

        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)

        if let color = NSColor(hexString: trimmed) {
            var item = ClipItem(kind: .color, isShelf: isShelf)
            item.text = trimmed
            item.detail = color.rgbDescription
            item.fingerprint = "color:" + trimmed.lowercased().sha256
            return item
        }

        var kind = ClipKind.text
        if let url = URL(string: trimmed),
           let scheme = url.scheme?.lowercased(),
           ["http", "https", "ftp", "mailto", "ssh"].contains(scheme),
           !trimmed.contains(" "), !trimmed.contains("\n") {
            kind = .link
        }

        var item = ClipItem(kind: kind, isShelf: isShelf)
        item.text = string
        if kind == .link, let host = URL(string: trimmed)?.host { item.detail = host }
        item.fingerprint = "\(kind.rawValue):" + string.sha256
        return item
    }

    // MARK: - Данные об источнике

    static func stampSource(_ item: inout ClipItem) {
        guard let app = NSWorkspace.shared.frontmostApplication,
              app.bundleIdentifier != Bundle.main.bundleIdentifier else { return }
        item.sourceName = app.localizedName
        item.sourceBundleID = app.bundleIdentifier
    }
}

extension NSColor {
    convenience init?(hexString: String) {
        var hex = hexString.trimmingCharacters(in: .whitespacesAndNewlines)
        guard hex.hasPrefix("#") else { return nil }
        hex.removeFirst()
        guard hex.count == 3 || hex.count == 6 || hex.count == 8,
              hex.allSatisfy({ $0.isHexDigit }) else { return nil }
        if hex.count == 3 { hex = hex.map { "\($0)\($0)" }.joined() }
        guard let value = UInt64(hex, radix: 16) else { return nil }
        let hasAlpha = hex.count == 8
        let r, g, b, a: CGFloat
        if hasAlpha {
            r = CGFloat((value >> 24) & 0xFF) / 255
            g = CGFloat((value >> 16) & 0xFF) / 255
            b = CGFloat((value >> 8) & 0xFF) / 255
            a = CGFloat(value & 0xFF) / 255
        } else {
            r = CGFloat((value >> 16) & 0xFF) / 255
            g = CGFloat((value >> 8) & 0xFF) / 255
            b = CGFloat(value & 0xFF) / 255
            a = 1
        }
        self.init(srgbRed: r, green: g, blue: b, alpha: a)
    }

    var rgbDescription: String {
        guard let c = usingColorSpace(.sRGB) else { return "" }
        return String(format: "rgb(%d, %d, %d)",
                      Int(round(c.redComponent * 255)),
                      Int(round(c.greenComponent * 255)),
                      Int(round(c.blueComponent * 255)))
    }
}
